server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          default-label: main
          uri: https://github.com/raquelsouto/microservice-repository
          search-paths: fornecedor, loja, transportador